project:
  type: website

website:
  title: "Home"
  navbar:
    right:
      - icon: github
        href: https://github.com/kazuyanagimoto/quarto-slides-typst

format:
  html:
    theme:
      - yeti
      - custom.scss

execute: 
  freeze: auto



